source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.4'
gem 'mysql2'
gem 'geokit-rails'
gem 'protected_attributes'
gem 'sass-rails', '~> 4.0.2'
gem 'coffee-rails', '~> 4.0.0'
gem 'execjs'
gem 'activeadmin', github: 'gregbell/active_admin'
gem 'jquery-rails'
gem 'jbuilder', '~> 1.2'
gem 'rspec-rails'
gem 'factory_girl_rails', '~> 4.0'
gem 'acts-as-taggable-on'

group :development do
 gem 'better_errors'
 gem 'binding_of_caller'
end



